"""
Django settings for ecomm project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9o(=8#_=yv^-3v7ab=lt5lq(5p658b6zix*hh#cqf9u5r#(-m)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cart_app.apps.CartAppConfig',
    'orders_app.apps.OrdersAppConfig',
    'payments_app.apps.PaymentsAppConfig',
    'products_app.apps.ProductsAppConfig',
    'shipping_app.apps.ShippingAppConfig',
    'users_app.apps.UsersAppConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'phonenumber_field',
    'drf_spectacular',
    'drf_spectacular_sidecar'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecomm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecomm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}


STRIPE_SECRET_KEY = "sk_test_51PyvDe2MqVpaBsk5gbcgKLxVeuK8iMUMctGEfMqbgmnaH0hNZCsTmX9JhpIgSI2C7flh4goy16XZCw03kXuw4GCj00zqEjgceh" # Change to ENV variables when deploying
SHIPPO_SECRET_KEY = "shippo_test_cb5894bf13971f0563e2273effa9482005d6d699" # Change to ENV variables when deploying


SHIPPING_ADDRESS_PERSON_NAME = "Shawn Ippotle"
SHIPPING_ADDRESS_STREET = "215 Clayton St."
SHIPPING_ADDRESS_CITY = "San Francisco"
SHIPPING_ADDRESS_STATE = "CA"
SHIPPING_ADDRESS_ZIP = "94117"
SHIPPING_COUNTRY = "US"
SHIPPING_PHONE_NUMBER = "+14185438090"
SHIPPING_EMAIL = "example@example.com"


SPECTACULAR_SETTINGS = {
    'TITLE': 'E-commerce Store RESTful API',
    'DESCRIPTION': '''This API powers the backend for an e-commerce platform, providing comprehensive management for products, users, orders, and reviews. It offers features to handle all aspects of an online store, from user authentication to product listings and order fulfillment.

Key Features:
- **User Management**: Secure user authentication, registration, login, and profile management. Roles include customers and admin users, with access control based on user roles.
- **Product Management**: Full CRUD functionality for managing products, including listing, creating, updating, and deleting products. Product categories, images, and inventory are also handled within the API. Admin access is required for product modifications.
- **Order Management**: Allows users to create and manage their orders. Admin users can view, update, and track order statuses for fulfillment.
- **Review System**: Registered users can submit, update, and delete product reviews. The API supports review filtering by product and user activity.
- **Rate Limiting**: Controls API usage with rate limits to ensure efficient performance for both anonymous and authenticated users.
- **Search and Filtering**: Supports product search and filtering based on various criteria such as categories, price range, and availability.

Please refer to the endpoints below for detailed operations and supported data structures in this API.''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
    },
}