# Generated by Django 5.1 on 2024-09-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_delivery_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='tracking_number',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
