# Generated by Django 5.1 on 2024-09-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_app', '0002_delivery_created_at_delivery_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('failed', 'Failed')], default=None, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='name',
            field=models.CharField(choices=[('shippo', 'Shippo')], max_length=6),
        ),
    ]
