# Generated by Django 5.1 on 2024-09-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_app', '0003_delivery_status_alter_shippingmethod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='shipping_label_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
